### PR TITLE
Fix serialization issues in HashMap, LinkedHashMap, HashSet and LinkedHashSet

### LINKED ISSUE #377: mutable HashSet/HashMap not serializable
```
scala>   def serializeDeserialize[T <: AnyRef](obj: T): T = {
     |     import java.io._
     |     val buffer = new ByteArrayOutputStream
     |     val out = new ObjectOutputStream(buffer)
     |     out.writeObject(obj)
     |     val in = new ObjectInputStream(new ByteArrayInputStream(buffer.toByteArray))
     |     in.readObject.asInstanceOf[T]
     |   }

scala> serializeDeserialize(mutable.HashSet())
java.io.NotSerializableException: scala.collection.mutable.FlatHashTable

scala> serializeDeserialize(mutable.HashMap())
java.io.NotSerializableException: scala.collection.mutable.HashMap$$anon$1
```

### PR DESCRIPTION
**Pull request by marcelocenerine**
This PR fixes #377. 

The reason for the `NotSerializableException`s is that the `HashTable`/`FlatHashTable` classes are not serializable nor the `table` fields in `HashMap`/`LinkedHashMap`/`HashSet`/`LinkedHashSet` classes are marked as transient. 

The easiest solution would be to make `HashTable`/`FlatHashTable` serializable. However, there are a few more issues here:

1. `out.defaultWriteObject` and `in.defaultReadObject` should be called from the `writeObject`/`readObject` methods of the class being serialized/deserialized (usually in the 1st line). Currently this is done from methods in `HashTable`/`FlatHashTable`, which is confusing and causes the issue below;
2. `table.init` is being called before `defaultReadObject`, which causes a NPE during deserialization (need to get past the `NotSerializableException` to see this one);
3. `HashMap`/`LinkedHashMap`/`LinkedHashSet` creates anonymous instances of `HashTable`. In Java (I assume the same applies to Scala) it is not recommended to serialize inner classes as these use compiler-generated synthetic fields to store references to enclosing instances and to store values of local variables from enclosing scopes (it is not a big deal now as the attributes in the enclosed classes are marked transient). Also, it's unspecified how these fields correspond to the class definition, as well as the names of anonymous and local classes.
4. `HashTable` and `FlatHashTable` are private classes in the `strawman.collection.mutable` package. If these classes are included in the serialized form of dependent classes, the former becomes part of the exported API of the latter. This decreases the flexibility to change them once they are released.

Issues 3 and 4 (name of anonymous and private classes leaking) are exemplified in the output below:

```
val obj = mutable.HashMap(1 -> "one", 2 -> "two", 3 -> "three")`:
val buffer = new ByteArrayOutputStream
val out = new ObjectOutputStream(buffer)
out.writeObject(obj)
println(new String(buffer.toByteArray)) 
```

```
��sr#strawman.collection.mutable.HashMapLtablet'Lstrawman/collection/mutable/HashTable;xpsr+strawman.collection.mutable.HashMap$$anon$1˜-���xr%strawman.collection.mutable.HashTab�srjava.lang.Integer⠤���8Ivaluexrjava.lang.Number���
                                                    ���xpttwosq~tonesq~tthreex
```

Below is the output for the same object after the changes in this PR were implemented:

```
�srjava.lang.Integer⠤���8Ivaluexrjava.lang.Number���
                                                    ���xpttwosq~tonesq~tthreex
```

### CODE REVIEW

File: test/junit/src/test/scala/strawman/collection/immutable/SerializationTest.scala [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+  def bitSet(): Unit = {
+    assertEqualsAfterDeserialization(BitSet.empty)
+    assertEqualsAfterDeserialization(BitSet(1, 2, 3))
+  }
+
+//  @Test
+//  def treeSet(): Unit = {
+//    assertEqualsAfterDeserialization(TreeSet.empty)
+//    assertEqualsAfterDeserialization(TreeSet(1, 2, 3))
+//  }
```
Comment (marcelocenerine) [inline test/junit/src/test/scala/strawman/collection/immutable/SerializationTest.scala]: bug?

File: test/junit/src/test/scala/strawman/collection/immutable/SerializationTest.scala [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+
+//  @Test
+//  def lazyList(): Unit = {
+//    assertEqualsAfterDeserialization(LazyList.empty)
+//    assertEqualsAfterDeserialization(LazyList.from(1))
+//  }
```
Comment (marcelocenerine) [inline test/junit/src/test/scala/strawman/collection/immutable/SerializationTest.scala]: `Stream` is serializable whereas `LazyList` is not.

Comment (marcelocenerine) [reply test/junit/src/test/scala/strawman/collection/immutable/SerializationTest.scala]: #331

**Comment by marcelocenerine** [comment]
I realized that `HashTable` and `FlatHashTable` both exist in `scala.collection`. However, they are public traits mixed in with maps/sets rather than private classes used in private fields. What I mentioned above is not relevant in that case.

**Comment by julienrf** [comment]
The motivation to use aggregation rather than inheritance was to simplify the public facing type hierarchy.

**Comment by marcelocenerine** [comment]
@szeiger / @lrytz, any inputs here?

File: collections/src/main/scala/strawman/collection/immutable/TreeSet.scala [hunk 3]
```diff
@@ -25,11 +25,13 @@ import scala.{Boolean, Int, math, NullPointerException, Option, Ordering, Some,
   *  @define mayNotTerminateInf
   *  @define willNotTerminateInf
   */
+@SerialVersionUID(-5685982407650748405L)
```
Comment (lrytz) [inline collections/src/main/scala/strawman/collection/immutable/TreeSet.scala]: I started writing a comment here, but actually let's leave it for now and come back to it later :-) https://github.com/scala/collection-strawman/issues/418

Comment (marcelocenerine) [reply collections/src/main/scala/strawman/collection/immutable/TreeSet.scala]: yeah, when I saw the issue you created it immediately came up to my mind.
