### PR TITLE
Add `@throws` annotations; fix iterators

### LINKED ISSUE #152: Add throw annotations
Add `@throws` annotations to relevant methods, such as `Iterator.next()` and `ArrayLike.apply(Int)`.

I don't know if this is a priority right now, but for both of the methods above (and there may be others), implementations should in most cases have a check which throws an appropriate exception, and `@throws` annotations might help to make that more obvious.

### PR DESCRIPTION
**Pull request by NthPortal**
Add `@throws` annotations for `Map.apply`, `Seq.apply` and `Iterator.next()`.

Fix two cases where iterators did not bounds check.

Attempts to resolve #152 (though I may not have thought of some methods which should have `@throws` annotations).

### CODE REVIEW

File: src/main/scala/strawman/collection/ArrayOps.scala [hunk 1]
```diff
@@ -19,6 +19,7 @@ class ArrayOps[A](val xs: Array[A])
   protected[this] def seq: Seq[A] = iterableFactory.fromIterable(coll)
 
   def length = xs.length
+  @throws[ArrayIndexOutOfBoundsException]
   def apply(i: Int) = xs.apply(i)
```
Comment (julienrf) [inline src/main/scala/strawman/collection/ArrayOps.scala]: Isn’t it enough to put the annotation on the parent (`ArrayLike`) class only?

Comment (NthPortal) [inline src/main/scala/strawman/collection/ArrayOps.scala]: There are a few reasons I added the annotation there.

- It is a more specific exception than that thrown by its `super`
- Though somewhat unlikely, the class could conceivably be inherited from (I've inherited from `Ordering.Ops` before)
- Even if not necessary for the implementer, it's helpful for a caller to be able to see that it throws an exception

Additionally, I don't feel that there's a significant cost incurred by adding the annotation, though you and others may disagree.

**Comment by julienrf** [comment]
Thanks :)
