### PR TITLE
Fix NPE in Iterator.addString when there are null elements

### LINKED ISSUE #378: NPE in AbstractIterator.mkString
`AbstractIterator.mkString` crashes with an NPE on null elements

```
scala> case class C(x: String)
defined class C

scala> C(null).toString
java.lang.NullPointerException
  at scala.collection.Iterator.$anonfun$addString$1(Iterator.scala:1113)
  at scala.collection.Iterator.foreach(Iterator.scala:427)
  at scala.collection.Iterator.foreach$(Iterator.scala:426)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1376)
  at scala.collection.Iterator.addString(Iterator.scala:1111)
  at scala.collection.Iterator.addString$(Iterator.scala:1107)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1376)
  at scala.collection.Iterator.mkString(Iterator.scala:1077)
  at scala.collection.Iterator.mkString$(Iterator.scala:1076)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1376)
  at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:143)

scala> C(null).productIterator.mkString(",")
java.lang.NullPointerException
  at scala.collection.Iterator.$anonfun$addString$1(Iterator.scala:1113)

scala> List.from(C(null).productIterator).mkString(",")
res10: String = null
```

### PR DESCRIPTION
**Pull request by marcelocenerine**
Fixes #378

### CODE REVIEW

File: collections/src/main/scala/strawman/collection/Iterator.scala [hunk 1]
```diff
@@ -1107,18 +1107,18 @@ trait Iterator[+A] extends IterableOnce[A] { self =>
...
     for (x <- self) {
       if (first) {
-        b addAll x.toString
+        b.append(x)
         first = false
       }
       else {
-        b addAll sep
-        b addAll x.toString
+        b.append(sep)
```
Comment (marcelocenerine) [inline collections/src/main/scala/strawman/collection/Iterator.scala]: `append(x: Any)` uses `String.valueOf(x)` which deals with null values

**Comment by julienrf** [comment]
Thanks @marcelocenerine!
