### PR TITLE
Bug fixes for Buffer/ArrayBuffer/ListBuffer

### LINKED ISSUE #413: filterInPlace throws exceptions and/or fails on many inputs
```
ArrayBuffer(1, 2).filterInPlace(_ => false)
```

is one such example of throwing an exception.  (`ArrayBuffer` always throws.)

`ListBuffer` returns incorrect results.

```
ListBuffer(1, 2).filterInPlace(_ => false)
```

returns `ListBuffer(2)`.

If anything else has `filterInPlace`, it is okay.

### PR DESCRIPTION
**Pull request by marcelocenerine**
This PR fixes #413, #409, #410, #406

My original goal was to fix #413 only. It turns out that I had to fix other bugs along the way to allow the original one to be fixed or was somehow related. Some of these bugs have issues and others don't (e.g. `ListBuffer.remove(idx)`, `Buffer.trimStart/trimEnd`, ...). Each fix is in a separate commit to ease the code review

There are still some bugs in those classes which are covered by other issues that @Ichoran has already filed

### CODE REVIEW

File: collections/src/main/scala/strawman/collection/mutable/Buffer.scala [hunk 1]
```diff
@@ -117,17 +129,18 @@ trait IndexedOptimizedBuffer[A] extends IndexedOptimizedSeq[A] with Buffer[A] {
...
+          this(j) = this(i)
+        }
         j += 1
       }
       i += 1
     }
-    takeInPlace(j)
+
+    if (i == j) this else takeInPlace(j)
   }
```
Comment (marcelocenerine) [inline collections/src/main/scala/strawman/collection/mutable/Buffer.scala]: #413

**Comment by julienrf** [comment]
Awesome, thanks!
